### ISSUE TITLE
Connection lost asks for unknown VNC SSH password

### ISSUE THREAD

**Issue by lferraro** [RemoteConnectionManager/RCM#27]
When a connection lost occurs, a dialog pops up asking for a VNC password (see below snapshot):

![rcm-vnc-authentication](https://user-images.githubusercontent.com/8280914/48768247-f1d1db80-ecb8-11e8-8f32-35547f3f8a76.png)

Of course this is not the user login password, but I guess an internal RCM password used to encrypt 
current connection. 

Can you set up an automatic reconnection mechanism which recovers internal VNC password without asking the user for it?

**Comment by luigi-calori** [comment]
Mmm.. you are right, the required password is the VNC one, encrypted. This password is passed to 
RCM to the vncviewer client.
It seems that the currnt behaviour of vncclinet when the connection times out is to ask for a reconnection. It would be better it just die, as it likely was in the past versions.
We can try to see if there is a flag that instruct vncviewer to avoid to try to connect and just die.
Unsure weather  the vnc password can be "saved" inside vncviewer so it automatically find it

**Comment by sbna** [comment]
I added the two flags -NoReconnect -NoNewConn. Dovrebbe aver risolto il problema. Se no riapro la issue
