### ISSUE TITLE
session name limitations

### ISSUE THREAD

**Issue by lferraro** [RemoteConnectionManager/RCM#28]
Dear developers, 

when you dealing with more username, sessions, machine and so on, it is very useful to provide meaningful (longer) session names.

can you support at least 32 characters in session name and include other common symbols such as "." (dot) and "-" hypen? 

![rcm-short-names](https://user-images.githubusercontent.com/8280914/49015921-c9e4eb00-f184-11e8-9a82-4ccd7e487b0c.png)

**Comment by sbna** [comment]
ok, I think now the session name length is 16

**Comment by sbna** [comment]
In the new version of RCM, the session name is generated automatically based on the user's choices
