### ISSUE TITLE
Fix windows build not finding vncvviewer >3 as entry point is a .bat file 

### ISSUE THREAD

**Issue by luigi-calori** [RemoteConnectionManager/RCM#38]
fix python which call that search vncviewer and bump out not finding .bat

**Comment by Giuncan** [comment]
Right now, the command `vncviewer.bat` starts a black cmd terminal.

**Comment by Giuncan** [comment]
The `which()` function is define in two different files:

* `rcm/client/logic/rcm_utils.py`
* `rcm/utils/executable.py`

**Comment by luigi-calori** [comment]
True, likely they have been implemented in different time, and used in different contexts, likely one is copied from spack.
We should decide for one and use it everywhere

**Comment by Giuncan** [comment]
Found known bug of `subprocess` with `shell=False`: https://github.com/python/cpython/issues/74268
